### ISSUE TITLE
#2 November Meetup

### ISSUE THREAD

**Issue by Kristories** [BekasiTechtalk/talks#3]
Silahkan tinggalkan komentar untuk topik di November Meetup.

Beberapa topik yang sudah kami catat : 

[![](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Git%20for%20Version%20Control)](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Git%20for%20Version%20Control/vote)
[![](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Project%20Management)](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Project%20Management/vote)
[![](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/ChatBot)](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/ChatBot/vote)
[![](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Android%20with%20NativeScript)](https://api.gh-polls.com/poll/01CTGBJMMXQ4V8FRQD5B40TY3N/Android%20with%20NativeScript/vote)

**Comment by cendekia** [comment]
> Silahkan tinggalkan komentar untuk topik di November Meetup.
> 
> Beberapa topik yang sudah kami catat :
> 
> * Git for Version Control
> * Project Management

* Cara membuat simple ChatBot (using botman.io)
* Cara mudah membuat Android Aplikasi dengan NativeScript

**Comment by imankubbil** [comment]
Android with NativeScript

**Comment by wadidin** [comment]
react-native
